// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

var NodeENV = process.env.NODE_ENV;

var plugins = [];

var definePlugin = new webpack.DefinePlugin({
  env:{
    isDevelopment:true
  }
});

plugins.push(definePlugin);

module.exports = {
  webpackDevPort: webpackDevPort,
  resolve: {
    extensions: ['', '.js','.jsx'],
  },
  externals:{
    pixi:'PIXI',
    PIXI:'PIXI',
  },
  entry: {
    index: path.resolve(__dirname, './public/js/main.jsx'),
  },
  output: {
    path: path.resolve(__dirname, './public/dist/'),
    publicPath: "http://localhost:" + webpackDevPort + "/public/dist",
    filename: '[name].js'
  },
  module: {
    loaders: [
      {
        test:/\.jsx|\.js$/,
        exclude: /node_modules|bower_components/,
        loader:'babel'
      },
      {
        test:/\.scss$/,
        exclude: /node_modules|bower_components/,
        loaders:['style','css','sass-loader']
      },{
        test:/\.css$/,
        exclude: /node_modules|bower_components/,
        loaders:['style','css']
      },{
        test:/\.ttf|otf$/,
        loaders:['file?name=/fonts//[name].[ext]']
      }
    ]
  },
  plugins:plugins,
  devtool: 'source-map'
};

//# sourceMappingURL=webpack.config.js.map
