// Generated by CoffeeScript 1.8.0
var path = require('path');

var webpack = require('webpack');

var webpackDevPort = 7301;

var NodeENV = process.env.NODE_ENV;

var base = require('./webpack.config');

base.plugins = [
  new webpack.DefinePlugin({
    env: {
      isDevelopment:false
    }
  }),
  new webpack.optimize.UglifyJsPlugin({
    compress:{
      warning:false
    }
  })
];

module.exports = base;