// Generated by CoffeeScript 1.8.0
var path = require('path');
var fs = require('fs');
var policyMap = {};
var jsFileReg = /\.js$/;
var files = fs.readdirSync(path.resolve(__dirname));

files.filter(function (name) {
  return jsFileReg.test(name);
}).map(function (nameWithExt) {
  return nameWithExt.replace(jsFileReg, '');
}).forEach(function (name) {
  return policyMap[name] = require("./" + name);
});

module.exports = function (policy) {
  return policyMap[policy];
};

//# sourceMappingURL=index.js.map
